apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  type: oci                          # ★ OCI 形式的 chart 仓库（ghcr.io）
  url: oci://ghcr.io/stefanprodan/charts
---
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo-helm            # ★ release 装到这个 ns
spec:
  interval: 1m0s
  chart:
    spec:
      chart: podinfo                 # chart 名
      version: ">=6.7.0"             # ★ 版本约束（SemVer 范围）
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      interval: 1m                   # chart 源的检查间隔
  values:                            # ★ 覆盖 values（对应 helm --set / -f）
    replicaCount: 2
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
