apiVersion: v1
kind: Secret
metadata:
    name: podinfo-secret
    namespace: podinfo
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:BApfJHaxovKr9UNTtpVEWPuyRY6Vsw==,iv:v3mtGqvedM2LfgKQCM9fLsiVD/4EWFPsEkYT4vA7G5U=,tag:qDWFqB9K0lfAVuAoUCOOwQ==,type:str]
sops:
    age:
        - recipient: age143njc5pxkg6ks3098r8urdsfve6u7hp4530e8ct8qsty0wrgmq7swud6wc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZ3kwRjRQdCtpUUY2b3NU
            dWNUVEF4MXJJL0ZpY1puYitXK0wwdlBjRHhjCkJDR1RZVUMvby9jTkpocGgxYmo4
            Y0N5dEtQSCt5ZVlLQ2VIWjhzZVdYb1EKLS0tIHZzRnNyeXI3cUF5aDBJaHRUV1hQ
            TFA0bG1USzBlQzRFTVhUaFU3azVRcWcK5mxAZ3RiP3bZvtVr2FsuWmPKnGtlD/q1
            akVClKA4tjjOH3DSKugCgsWgj36GuCkUe408T7IiVG3G6x8d3pDzgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T03:20:59Z"
    mac: ENC[AES256_GCM,data:Yf39HYpTU4zhgmZkf2+RtmIkmpA84FYu4ioY7ZqJUBJDydqKIUSM92T6hg+NKn7g5fS+Qyytzb7sBgjtgnOu6Qhk77LA2J7a3ZMcZCVn1mhXPWOHedhWAzl6ELtjbYs52zS0snUJWJdKaDpLBwtsUb6KRPakLNPGf1w56X7NIHg=,iv:rDSTCFjj8WWzlJOY5JOlDzr6NSARgQ0FdgN2JVKPCq0=,tag:sD3dFPMXWLQV8exWIb6xwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
